import Link from 'next/link'
import './globals.css'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'Project IAE',
  description: 'This page will talk about IAE generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
