import './ceibal.css'
import LinkCeibal from '../components/LinkCeibal'
import ButtonPage from '../components/Button'

export default function Ceibal() {
  return (
    <main className="top">
      <section className="ceibal home">
        {/* INTENTAR CARGAR IMAGENES EDITADAS (CENTRADAS Y CON DISTINTO PESO) PARA DESKTOP Y MOBILE */}

        <LinkCeibal
          href={'https://ceibal.edu.uy/institucional/que-es-ceibal/'}
          cls={'d1'}
          cls3="horizontal"
          cls4="horizontal2"
          src={'/image/ceibal-11.jpg'}
          src2={'/image/ceibal.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d2'}
          cls2="hidden2"
          cls4="hidden3"
          src={'/image/ceibal-ingles2.png'}
          src2={'/image/ceibal-ingles.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d3'}
          cls2="hidden2"
          cls3="vertical"
          cls4="vertical2 hidden3"
          src={'/image/ceibal-ia2.png'}
          src2={'/image/ceibal-vertical.jpg'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d4'}
          src={'/image/ceibal-crea.jpg'}
          src2={'/image/crea-20.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d5'}
          src={'/image/ceibal-micro2.jpg'}
          src2={'/image/ceibal-micro.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d6'}
          src={'/image/ceibal-18anios.png'}
          src2={'/image/ceibal-4.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d7'}
          src={'/image/ceibal-2.png'}
          src2={'/image/ceibal-territorio.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d8'}
          src={'/image/ceibal-ciencias.jpeg'}
          src2={'/image/ceibal-ciencias2.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d9'}
          cls3="horizontal"
          cls4="horizontal2"
          src={'/image/ceibal-stemv2.png'}
          src2={'/image/ceibal-stem2v2.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d10'}
          cls2="hidden2"
          cls3="vertical"
          cls4="vertical2 hidden3"
          src={'/image/ceibal-biblioteca4.png'}
          src2={'/image/ceibal-biblioteca3.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d11'}
          src={'/image/ceibal-ciudadania.jpg'}
          src2={'/image/ceibal-ciudadania2.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d12'}
          src={'/image/ceibal-campus.jpg'}
          src2={'/image/ceibal-3.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d13'}
          src={'/image/ceibal-jovenes2.jpg'}
          src2={'/image/ceibal-jovenes.jpg'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d14'}
          src={'/image/ceibal-aleks.png'}
          src2={'/image/ceibal-aleks2.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d15'}
          src={'/image/ceibal-matific.jpg'}
          src2={'/image/ceibal-matific2.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d16'}
          cls3="horizontal"
          cls4="horizontal2"
          src={'/image/ceibal-edux.png'}
          src2={'/image/ceibal-edux2.png'}
          alt={'Image'}
        />
        <LinkCeibal
          href={'https://www.google.com'}
          cls={'d17'}
          src={'/image/ceibal-lengua.png'}
          src2={'/image/ceibal-lengua2.png'}
          alt={'Image'}
        />
       <LinkCeibal
          href={'https://ceibal.edu.uy/institucional/que-es-ceibal/'}
          cls={'d18'}
          cls3="horizontal"
          cls4="horizontal2"
          src={'/image/ceibal-11.jpg'}
          src2={'/image/ceibal.png'}
          alt={'Image'}
        />
        <ButtonPage href="./breaks" className="ceibal__link">
          Previous
        </ButtonPage>
      </section>
    </main>
  )
}
